# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'PortalsEcommerce' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PortalsEcommerce
  pod 'Capacitor'
  pod 'IonicPortals', '~> 0.6.0'
  pod "CapacitorCamera"

end
